
spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URL}


server:
  port: 8017

logging:
  file:
    name: logs/testangproj1.log
    path: testangproj1
  level:
    com.geppetto: info
  pattern:
    dateformat: "dd-MM-yyyy hh:mm:ss aa"